-- MySQL Script generated by MySQL Workbench
-- 01/13/15 15:38:08
-- Model: WetDB    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wetdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wetdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wetdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wetdb` ;

-- -----------------------------------------------------
-- Table `wetdb`.`connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`connections` (
  `id_odbcdsn` INT NOT NULL AUTO_INCREMENT,
  `odbc_dsn` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id_odbcdsn`),
  UNIQUE INDEX `id_odbcdsn_UNIQUE` (`id_odbcdsn` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`measures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`measures` (
  `id_measures` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `description` VARCHAR(512) NULL,
  `type` INT NOT NULL DEFAULT 0,
  `reliable` TINYINT(1) NOT NULL DEFAULT 1,
  `update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `min_night_start_time` TIME NOT NULL,
  `min_night_stop_time` TIME NOT NULL,
  `max_day_start_time_1` TIME NOT NULL,
  `max_day_stop_time_1` TIME NOT NULL,
  `max_day_start_time_2` TIME NOT NULL,
  `max_day_stop_time_2` TIME NOT NULL,
  `max_day_start_time_3` TIME NOT NULL,
  `max_day_stop_time_3` TIME NOT NULL,
  `energy_category` INT NULL DEFAULT 0,
  `energy_specific_content` DOUBLE NULL DEFAULT 0.0,
  `strumentation_type` INT NULL,
  `strumentation_model` VARCHAR(255) NULL,
  `strumentation_serial_number` VARCHAR(255) NULL,
  `strumentation_link_type` INT NULL,
  `sap_code` VARCHAR(255) NULL,
  `fixed_value` DOUBLE NOT NULL DEFAULT 0.0,
  `epanet_object_id` VARCHAR(255) NULL,
  `critical` TINYINT(1) NOT NULL DEFAULT 0,
  `x_position` DOUBLE NULL,
  `y_position` DOUBLE NULL,
  `z_position` DOUBLE NULL,
  `alarm_thresholds_enable` TINYINT(1) NOT NULL DEFAULT 0,
  `alarm_min_threshold` DOUBLE NOT NULL DEFAULT 0.0,
  `alarm_max_threshold` DOUBLE NOT NULL DEFAULT 0.0,
  `alarm_constant_check_enable` TINYINT(1) NOT NULL DEFAULT 0,
  `alarm_constant_hysteresis` DOUBLE NOT NULL DEFAULT 0.0,
  `alarm_constant_check_time` INT NOT NULL DEFAULT 0,
  `table_name` VARCHAR(255) NOT NULL DEFAULT '',
  `table_relational_id_column` VARCHAR(255) NULL,
  `table_relational_id_value` VARCHAR(255) NULL,
  `table_relational_id_type` INT NULL,
  `table_timestamp_column` VARCHAR(255) NOT NULL DEFAULT '',
  `table_value_column` VARCHAR(255) NOT NULL DEFAULT '',
  `map` LONGTEXT NULL,
  `connections_id_odbcdsn` INT NOT NULL,
  PRIMARY KEY (`id_measures`, `connections_id_odbcdsn`),
  UNIQUE INDEX `id_measures_UNIQUE` (`id_measures` ASC),
  INDEX `fk_measures_connections1_idx` (`connections_id_odbcdsn` ASC),
  CONSTRAINT `fk_measures_connections1`
    FOREIGN KEY (`connections_id_odbcdsn`)
    REFERENCES `wetdb`.`connections` (`id_odbcdsn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`districts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`districts` (
  `id_districts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `zone` VARCHAR(255) NULL,
  `class` INT NOT NULL,
  `municipality` VARCHAR(255) NULL,
  `inhabitants` BIGINT NULL,
  `update_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `min_night_start_time` TIME NOT NULL,
  `min_night_stop_time` TIME NOT NULL,
  `max_day_start_time_1` TIME NOT NULL,
  `max_day_stop_time_1` TIME NOT NULL,
  `max_day_start_time_2` TIME NOT NULL,
  `max_day_stop_time_2` TIME NOT NULL,
  `max_day_start_time_3` TIME NOT NULL,
  `max_day_stop_time_3` TIME NOT NULL,
  `unitary_phisiological_nigth_demand` DOUBLE NULL DEFAULT 2,
  `properties` DOUBLE NULL,
  `rewarded_water` DOUBLE NULL,
  `billing` DECIMAL(10,2) NULL DEFAULT 1.80,
  `not_household_night_use` DOUBLE NULL DEFAULT 0.0,
  `length_main` DOUBLE NULL DEFAULT 0.0,
  `average_zone_night_pressure` DOUBLE NULL DEFAULT 0.0,
  `household_night_use` DOUBLE NULL DEFAULT 0.0,
  `alpha_emitter_exponent` DOUBLE NULL DEFAULT 0.0,
  `sap_code` VARCHAR(255) NULL,
  `ev_enable` TINYINT(1) NOT NULL DEFAULT 1,
  `ev_bands_autoupdate` TINYINT(1) NOT NULL DEFAULT 0,
  `ev_high_band` DOUBLE NOT NULL DEFAULT 0.0,
  `ev_low_band` DOUBLE NOT NULL DEFAULT 0.0,
  `ev_statistic_high_band` DOUBLE NOT NULL DEFAULT 0.0,
  `ev_statistic_low_band` DOUBLE NOT NULL DEFAULT 0.0,
  `ev_variable_type` INT NOT NULL DEFAULT 0,
  `ev_last_good_sample_day` DATE NOT NULL,
  `ev_last_good_samples` INT NOT NULL DEFAULT 10,
  `ev_alpha` INT NOT NULL DEFAULT 2,
  `ev_samples_trigger` INT NOT NULL DEFAULT 3,
  `notes` TEXT NULL,
  `map` LONGTEXT NULL,
  `reset_all_data` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_districts`),
  UNIQUE INDEX `id_districts_UNIQUE` (`id_districts` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`data_measures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`data_measures` (
  `timestamp` DATETIME NOT NULL,
  `reliable` TINYINT(1) NOT NULL,
  `value` DOUBLE NOT NULL,
  `measures_id_measures` INT NOT NULL,
  `measures_connections_id_odbcdsn` INT NOT NULL,
  PRIMARY KEY (`timestamp`, `measures_id_measures`, `measures_connections_id_odbcdsn`),
  INDEX `fk_data_measures_measures1_idx` (`measures_id_measures` ASC, `measures_connections_id_odbcdsn` ASC),
  CONSTRAINT `fk_data_measures_measures1`
    FOREIGN KEY (`measures_id_measures` , `measures_connections_id_odbcdsn`)
    REFERENCES `wetdb`.`measures` (`id_measures` , `connections_id_odbcdsn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`data_districts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`data_districts` (
  `timestamp` DATETIME NOT NULL,
  `reliable` TINYINT(1) NOT NULL DEFAULT 1,
  `value` DOUBLE NOT NULL,
  `districts_id_districts` INT NOT NULL,
  PRIMARY KEY (`timestamp`, `districts_id_districts`),
  INDEX `fk_data_districts_districts1_idx` (`districts_id_districts` ASC),
  CONSTRAINT `fk_data_districts_districts1`
    FOREIGN KEY (`districts_id_districts`)
    REFERENCES `wetdb`.`districts` (`id_districts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`districts_day_statistic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`districts_day_statistic` (
  `day` DATE NOT NULL,
  `day_type` INT NOT NULL,
  `min_night` DOUBLE NULL,
  `min_day` DOUBLE NULL,
  `max_day` DOUBLE NULL,
  `avg_day` DOUBLE NULL,
  `standard_deviation` DOUBLE NULL,
  `real_leakage` DOUBLE NULL,
  `volume_real_losses` DOUBLE NULL,
  `range` DOUBLE NULL,
  `mnf_pressure` DOUBLE NULL,
  `min_night_pressure` DOUBLE NULL,
  `ideal_night_use` DOUBLE NULL,
  `districts_id_districts` INT NOT NULL,
  PRIMARY KEY (`day`, `districts_id_districts`),
  INDEX `fk_day_statistic_districts1_idx` (`districts_id_districts` ASC),
  CONSTRAINT `fk_day_statistic_districts1`
    FOREIGN KEY (`districts_id_districts`)
    REFERENCES `wetdb`.`districts` (`id_districts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `role` INT NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NULL,
  `email_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `email` VARCHAR(255) NULL,
  `sms_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `telephone_number` VARCHAR(255) NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `idusers_UNIQUE` (`idusers` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`lcf_identities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`lcf_identities` (
  `table_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `municipality` VARCHAR(255) NULL,
  PRIMARY KEY (`table_name`),
  UNIQUE INDEX `table_name_UNIQUE` (`table_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`lcf_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`lcf_data` (
  `timestamp` DATETIME NOT NULL,
  `ft1` DOUBLE NULL,
  `pt1` DOUBLE NULL,
  `pt2` DOUBLE NULL,
  `counter` DOUBLE NULL,
  `lcf_identities_table_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`timestamp`, `lcf_identities_table_name`),
  INDEX `fk_lcf_data_lcf_identities1_idx` (`lcf_identities_table_name` ASC),
  CONSTRAINT `fk_lcf_data_lcf_identities1`
    FOREIGN KEY (`lcf_identities_table_name`)
    REFERENCES `wetdb`.`lcf_identities` (`table_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`measures_has_districts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`measures_has_districts` (
  `measures_id_measures` INT NOT NULL,
  `measures_connections_id_odbcdsn` INT NOT NULL,
  `districts_id_districts` INT NOT NULL,
  `sign` INT NOT NULL,
  PRIMARY KEY (`measures_id_measures`, `measures_connections_id_odbcdsn`, `districts_id_districts`),
  INDEX `fk_measures_has_districts_districts1_idx` (`districts_id_districts` ASC),
  INDEX `fk_measures_has_districts_measures1_idx` (`measures_id_measures` ASC, `measures_connections_id_odbcdsn` ASC),
  CONSTRAINT `fk_measures_has_districts_measures1`
    FOREIGN KEY (`measures_id_measures` , `measures_connections_id_odbcdsn`)
    REFERENCES `wetdb`.`measures` (`id_measures` , `connections_id_odbcdsn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_measures_has_districts_districts1`
    FOREIGN KEY (`districts_id_districts`)
    REFERENCES `wetdb`.`districts` (`id_districts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`measures_day_statistic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`measures_day_statistic` (
  `day` DATE NOT NULL,
  `day_type` INT NOT NULL,
  `min_night` DOUBLE NULL,
  `min_day` DOUBLE NULL,
  `max_day` DOUBLE NULL,
  `avg_day` DOUBLE NULL,
  `standard_deviation` DOUBLE NULL,
  `range` DOUBLE NULL,
  `measures_id_measures` INT NOT NULL,
  `measures_connections_id_odbcdsn` INT NOT NULL,
  PRIMARY KEY (`day`, `measures_id_measures`, `measures_connections_id_odbcdsn`),
  INDEX `fk_measure_day_statistic_measures1_idx` (`measures_id_measures` ASC, `measures_connections_id_odbcdsn` ASC),
  CONSTRAINT `fk_measure_day_statistic_measures1`
    FOREIGN KEY (`measures_id_measures` , `measures_connections_id_odbcdsn`)
    REFERENCES `wetdb`.`measures` (`id_measures` , `connections_id_odbcdsn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`districts_statistic_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`districts_statistic_profiles` (
  `timestamp` DATETIME NOT NULL,
  `losses` DOUBLE NOT NULL,
  `theoretical_trend` DOUBLE NOT NULL,
  `districts_id_districts` INT NOT NULL,
  PRIMARY KEY (`timestamp`, `districts_id_districts`),
  INDEX `fk_district_statistic_profiles_districts1_idx` (`districts_id_districts` ASC),
  CONSTRAINT `fk_district_statistic_profiles_districts1`
    FOREIGN KEY (`districts_id_districts`)
    REFERENCES `wetdb`.`districts` (`id_districts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`measures_energy_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`measures_energy_profile` (
  `timestamp` DATETIME NOT NULL,
  `reliable` TINYINT(1) NOT NULL,
  `value` DOUBLE NOT NULL,
  `measures_id_measures` INT NOT NULL,
  `measures_connections_id_odbcdsn` INT NOT NULL,
  PRIMARY KEY (`timestamp`, `measures_id_measures`, `measures_connections_id_odbcdsn`),
  INDEX `fk_measure_energy_profile_measures1_idx` (`measures_id_measures` ASC, `measures_connections_id_odbcdsn` ASC),
  CONSTRAINT `fk_measure_energy_profile_measures1`
    FOREIGN KEY (`measures_id_measures` , `measures_connections_id_odbcdsn`)
    REFERENCES `wetdb`.`measures` (`id_measures` , `connections_id_odbcdsn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`districts_energy_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`districts_energy_profile` (
  `timestamp` DATETIME NOT NULL,
  `reliable` TINYINT(1) NOT NULL,
  `value` DOUBLE NOT NULL,
  `districts_id_districts` INT NOT NULL,
  PRIMARY KEY (`timestamp`, `districts_id_districts`),
  INDEX `fk_district_energy_profile_districts1_idx` (`districts_id_districts` ASC),
  CONSTRAINT `fk_district_energy_profile_districts1`
    FOREIGN KEY (`districts_id_districts`)
    REFERENCES `wetdb`.`districts` (`id_districts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`districts_energy_day_statistic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`districts_energy_day_statistic` (
  `day` DATE NOT NULL,
  `day_type` INT NOT NULL,
  `epd` DOUBLE NULL,
  `ied` DOUBLE NULL,
  `iela` DOUBLE NULL,
  `districts_id_districts` INT NOT NULL,
  PRIMARY KEY (`day`, `districts_id_districts`),
  INDEX `fk_district_energy_day_statistic_districts1_idx` (`districts_id_districts` ASC),
  CONSTRAINT `fk_district_energy_day_statistic_districts1`
    FOREIGN KEY (`districts_id_districts`)
    REFERENCES `wetdb`.`districts` (`id_districts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`districts_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`districts_events` (
  `day` DATE NOT NULL,
  `type` INT NOT NULL,
  `measure_type` INT NOT NULL,
  `duration` INT NULL DEFAULT 0,
  `value` DOUBLE NULL,
  `delta_value` DOUBLE NULL,
  `ranking` DOUBLE NULL,
  `description` VARCHAR(255) NULL,
  `districts_id_districts` INT NOT NULL,
  PRIMARY KEY (`day`, `districts_id_districts`),
  INDEX `fk_districts_events_districts1_idx` (`districts_id_districts` ASC),
  CONSTRAINT `fk_districts_events_districts1`
    FOREIGN KEY (`districts_id_districts`)
    REFERENCES `wetdb`.`districts` (`id_districts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`users_has_districts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`users_has_districts` (
  `users_idusers` INT NOT NULL,
  `districts_id_districts` INT NOT NULL,
  `events_notification` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`users_idusers`, `districts_id_districts`),
  INDEX `fk_users_has_districts_districts1_idx` (`districts_id_districts` ASC),
  INDEX `fk_users_has_districts_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_users_has_districts_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `wetdb`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_districts_districts1`
    FOREIGN KEY (`districts_id_districts`)
    REFERENCES `wetdb`.`districts` (`id_districts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`map_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`map_view` (
  `id_map_view` INT NOT NULL,
  `kml` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_map_view`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`districts_bands_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`districts_bands_history` (
  `timestamp` DATETIME NOT NULL,
  `high_band` DOUBLE NOT NULL,
  `low_band` DOUBLE NOT NULL,
  `districts_id_districts` INT NOT NULL,
  PRIMARY KEY (`timestamp`, `districts_id_districts`),
  INDEX `fk_districts_bands_history_districts1_idx` (`districts_id_districts` ASC),
  CONSTRAINT `fk_districts_bands_history_districts1`
    FOREIGN KEY (`districts_id_districts`)
    REFERENCES `wetdb`.`districts` (`id_districts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wetdb`.`measures_alarms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wetdb`.`measures_alarms` (
  `timestamp` DATETIME NOT NULL,
  `alarm_type` INT NOT NULL,
  `event_type` INT NOT NULL,
  `alarm_value` DOUBLE NOT NULL,
  `reference_value` DOUBLE NULL,
  `duration` TIME NULL,
  `measures_id_measures` INT NOT NULL,
  `measures_connections_id_odbcdsn` INT NOT NULL,
  PRIMARY KEY (`timestamp`, `measures_id_measures`, `measures_connections_id_odbcdsn`),
  INDEX `fk_measures_alarms_measures1_idx` (`measures_id_measures` ASC, `measures_connections_id_odbcdsn` ASC),
  CONSTRAINT `fk_measures_alarms_measures1`
    FOREIGN KEY (`measures_id_measures` , `measures_connections_id_odbcdsn`)
    REFERENCES `wetdb`.`measures` (`id_measures` , `connections_id_odbcdsn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE USER 'wet_admin' IDENTIFIED BY 'wet_admin';

GRANT ALL ON wetdb.* TO 'wet_admin';
CREATE USER 'wet_user' IDENTIFIED BY 'wet_user';

GRANT SELECT ON TABLE `wetdb`.* TO 'wet_user';
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE `wetdb`.`users` TO 'wet_user';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `wetdb`.`users_has_districts` TO 'wet_user';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `wetdb`.`measures` TO 'wet_user';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `wetdb`.`measures_has_districts` TO 'wet_user';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `wetdb`.`districts` TO 'wet_user';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `wetdb`.`map_view` TO 'wet_user';
GRANT INSERT, SELECT ON TABLE `wetdb`.`districts_bands_history` TO 'wet_user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
